apiVersion: app.bex.co/v1alpha1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/managed-by: kustomize
  name: service-sample
spec:
  # TODO(user): Add fields here
